
version: "3"
services:
  apache:
    build: ./apache
    command: bash -c "sleep 20 && php artisan migrate --no-interaction --force && apachectl -D FOREGROUND"
    container_name:
      "apache"
    ports: 
      - 80:80
    depends_on:
      - mysql
    restart: always
    env_file:
      -  env/apache_env
  mysql:
    image: mysql
    env_file:
      -  env/mysql_env
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    container_name:
      "mysql"
    restart: always

